# Project information
site_name: AI Cookbook

# Define TOC or order of website
nav:
  - Home: index.md
  - Python: Python.md
  - Machine Learning: ML.md
  - Deep Learning: DL.md
  - MLOps: MLOps.md
  - Big Data: BigData.md
  - Data Analytics: DataAnalytics.md
  - Research Papers: ResearchPapers.md
  - Feedback: Feedback.md

site_author: Vishal Singh
site_description: >-
  Everything you need for your AI journey..

# Repository
repo_name: AI Cookbook
repo_url: https://github.com/vishalsingh17/mkdocs-demo

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - header.autohide
    - announce.dismiss
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: lime    

  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/vishalsingh17/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/vishalsingh1719/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/vishal_singh17/
  version:
    provider: VS17
    default: stable
  analytics:
    provider: google
    property: G-AI Cookbook

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/vishalsingh17/"  target="_blank" rel="noopener">Vishal Singh</a>
